#!/usr/bin/env php
<?php

if (is_dir(__DIR__."/vendor/")) {
	require_once __DIR__ . '/vendor/autoload.php';
} else {
	require_once __DIR__ . '/../../autoload.php';
}

use Symfony\Component\Console\Application;
use \Core\Console\Console;

$application = new Application();

$console = Console::getInstance();
$console->bind($application);

$application->run();