<?php

namespace Core\System\Cron;

use Jobby\Jobby;

class Cron extends Jobby
{

	protected $jobList = [];

	protected function getJobName() : string
	{
		return "__INTERNAL_JOB__".count($this->jobs);
	}

	public function include($command, $value, $jobName = null) : Job
	{
		$jobName = $jobName ?? $this->getJobName();
		$job = new Job($command, $value);
		$this->jobList[$jobName] = $job;
		return $job;
	}

	public function closure(\Closure $value, $jobName = null) : Job
	{
		return $this->include("closure", $value, $jobName);
	}

	public function command($value, $jobName = null) : Job
	{
		return $this->include("command", $value, $jobName);
	}

	public function run()
	{
		foreach ($this->jobList as $name => $job) {
			$this->add($name, (array)$job);
		}
		return parent::run(); // TODO: Change the autogenerated stub
	}
}