<?php

namespace Core\System\Cron;

use Jobby\Jobby;

class Cron extends Jobby
{

	protected $jobList = [];

	protected function getJobName() : string
	{
		return "__INTERNAL_JOB__".count($this->jobs);
	}

	public function include($command, $value) : Job
	{
		$job = new Job($command, $value);
		$this->jobList[$this->getJobName()] = $job;
		return $job;
	}

	public function closure(\Closure $value) : Job
	{
		return $this->include("closure", $value);
	}

	public function command($value) : Job
	{
		return $this->include("command", $value);
	}

	public function run()
	{
		foreach ($this->jobList as $name => $job) {
			$this->add($name, (array)$job);
		}
		return parent::run(); // TODO: Change the autogenerated stub
	}
}