<?php

namespace Core\Console\Commands\Module;

use Core\Console\Commands\StubCommand;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;

class Base extends StubCommand
{

	protected $name;

	protected $command;

	protected $module;

	protected function getStub() : ?string
	{
		return file_get_contents(__DIR__."/template/{$this->name}.stub");
	}

	protected function getPath() : string
	{
		return config('system.modulesPath') . DIRECTORY_SEPARATOR . $this->module . DIRECTORY_SEPARATOR . $this->module . Str::studly($this->name) . '.php';
	}

	protected function configure()
	{
		$this
			->setName($this->command)
			->setDescription("Creates a/an {$this->name} file for a module")
			->setHelp("This command creates a/an {$this->name} file into the defined module folder")
			->addArgument("module", InputArgument::REQUIRED, "Name of the module")
		;
	}

	protected function setInfo($stub) : string
	{
		$this->module = Str::studly($this->input->getArgument('module'));
		$stub = str_replace("{{module}}", $this->module, $stub);
		return str_replace("{{module_studly}}", Str::studly($this->module), $stub);
	}

	protected function setFile($filepath, $stub)
	{
		$modulePath = pathinfo($filepath);
		if (!is_dir($modulePath['dirname'])) {
			mkdir($modulePath['dirname'], 0755);
		}
		parent::setFile($filepath, $stub); // TODO: Change the autogenerated stub
	}
}